# Setup
title:               'Álgebra'
tagline:             'Grado en Estadística'
description:         'Página con guiones de la asignatura'
url:                 ''
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Diego Ruano

# Gems
plugins:
  - jekyll-paginate

#gems: [jekyll-paginate]  
  
# Custom vars
version:             1.1.0

